CfgVars = { }

CfgVars["lottery"] = 1 --Lottery is enabled or disabled

CfgVars["lottoticketcost"] = 100 --How much each ticket costs
CfgVars["lottoautodraw"] = 9 --When this many tickets have been sold, automatically pick a number. set to 0 for NEVER auto draw
CfgVars["lottodrawtime"] = 300 --How long between each number being called (provided that the autodraw doesnt kick in). 0 for NEVER draw (except for auto)

CfgVars["warrantcost"] = 50
CfgVars["jeepcost"] = 500
CfgVars["armorcost"] = 400
CfgVars["steroidcost"] = 600
CfgVars["magicbulletcost"] = 450
CfgVars["allowturrets"] = 1
CfgVars["allowsteroids"] = 1
CfgVars["allowjeeps"] = 1
CfgVars["hltvproxywashere"] = 1
CfgVars["allowhelmet"] = 1
CfgVars["helmetcost"] = 100
CfgVars["turretcost"] = 300
CfgVars["turretmax"] = 3
CfgVars["airboatcost"] = 400
CfgVars["allowairboats"] = 1
CfgVars["allowdispensers"] = 1
CfgVars["dispensercost"] = 400
CfgVars["dispensermax"] = 2
CfgVars["spawncost"] = 150
CfgVars["allowspawn"] = 1
CfgVars["allowregen"] = 1
CfgVars["regencost"] = 700
CfgVars["allowshield"] = 1
CfgVars["shieldcost"] = 100
CfgVars["ampcost"] = 600
CfgVars["allowamp"] = 1
CfgVars["painkillercost"] = 500
CfgVars["allowpainkiller"] = 1
CfgVars["knifecost"] = 150
CfgVars["lockpickcost"] = 150
CfgVars["weldercost"] = 750
CfgVars["allowwelder"] = 1
CfgVars["maxprinters"] = 2
CfgVars["bigbombcost"] = 5000
CfgVars["pipebombcost"] = 150
CfgVars["gasgrenadecost"] = 400
CfgVars["molotovcost"] = 400
CfgVars["maxstills"] = 8
CfgVars["stillcost"] = 150
CfgVars["rpgcost"] = 1900
CfgVars["galilcost"] = 1700
CfgVars["ammorocketcost"] = 50
CfgVars["ammosnipercost"] = 60
CfgVars["ammodartcost"] = 50
CfgVars["ammofuelcost"] = 70
CfgVars["printercost"] = 1000
CfgVars["paracost"] = 2800
CfgVars["autosnipecost"] = 3500
CfgVars["augcost"] = 1800
CfgVars["autoshotguncost"] = 2400
CfgVars["uspcost"] = 220
CfgVars["mac10pistcost"] = 420
CfgVars["tmppistcost"] = 530
CfgVars["elitescost"] = 350
CfgVars["dartguncost"] = 300
CfgVars["maxhitman"] = 3
CfgVars["maxspec"] = 4
CfgVars["gunvaultcost"] = 300
CfgVars["gunfactorycost"] = 1000
CfgVars["maxgunfactory"] = 1
CfgVars["maxgunvaults"] = 5
CfgVars["pillboxcost"] = 300
CfgVars["allowreflect"] = 1
CfgVars["reflectcost"] = 600
CfgVars["drugfactorycost"] = 500
CfgVars["maxdrugfactory"] = 2
CfgVars["worldslayercost"] = 2500
CfgVars["allowfocus"] = 1
CfgVars["focuscost"] = 300
CfgVars["scannercost"] = 200
CfgVars["allowantidote"] = 1
CfgVars["antidotecost"] = 400
CfgVars["generatorcost"] = 400
CfgVars["shockwavecost"] = 600
CfgVars["doubletapcost"] = 750
CfgVars["knockbackcost"] = 400
CfgVars["magicbulletcost"] = 300
CfgVars["leechcost"] = 400
CfgVars["adrenalinecost"] = 400
CfgVars["doublejumpcost"] = 400
CfgVars["radartowercost"] = 500
CfgVars["armorpiercercost"] = 400
CfgVars["maxgenerator"] = 5
CfgVars["maxmethlab"] = 3
CfgVars["methlabcost"] = 600
CfgVars["toolkitcost"] = 150
CfgVars["maxweed"] = 10
CfgVars["weedcost"] = 50
CfgVars["steroidduration"] = 140
CfgVars["regenduration"] = 120
CfgVars["ampduration"] = 120
CfgVars["painkillerduration"] = 140
CfgVars["reflectduration"] = 110
CfgVars["focusduration"] = 120
CfgVars["antidoteduration"] = 150
CfgVars["magicbulletduration"] = 110
CfgVars["leechduration"] = 140
CfgVars["doubletapduration"] = 120
CfgVars["shockwaveduration"] = 130
CfgVars["doublejumpduration"] = 130
CfgVars["knockbackduration"] = 110
CfgVars["adrenalineduration"] = 150
CfgVars["armorpiercerduration"] = 110
CfgVars["randomduration"] = 180
CfgVars["superduration"] = 180
CfgVars["uberduration"] = 300
CfgVars["scancost"]=25
CfgVars["maxsigns"]=4
CfgVars["flamethrowercost"]=2100
CfgVars["tmpcost"]=1200

CfgVars["ooc"] = 1; --OOC allowed
CfgVars["alltalk"] = 1; --All talk allowed
CfgVars["crosshair"] = 1; --Crosshairs enabled?
CfgVars["maxmayor"] = 1; --Maximum amount of Mayors you can have
CfgVars["maxcps"] = 4; --Max number of CPs you can have
CfgVars["strictsuicide"] = 0; --Should players respawn where they suicided (regardless of they're arrested or not)
CfgVars["propertytax"] = 1; --Property taxes
CfgVars["cit_propertytax"] = 0; --Just citizens have to pay property tax?
CfgVars["paydelay"] = 60; --Pay day delay (in seconds)
CfgVars["banprops"] = 1; --Prop banning
CfgVars["toolgun"] = 1; --Tool gun enabled?
CfgVars["allowedprops"] = 0; --Should players be only able to spawn "allowed" props?
CfgVars["propspawning"] = 1; --Prop spawning enabled?
CfgVars["adminsents"] = 1; --Should all SENTs be admin only?
CfgVars["adminsweps"] = 1; --Should all sweps be admin only?
CfgVars["cpvote"] = 1; --Should people be able to use /votecop?
CfgVars["mayorvote"] = 1; --Should people be able to use /votemayor?
CfgVars["enforceplayermodel"] = 1; --Should player models be enforced? (Bans using player models like zombie/combine/etc)
CfgVars["proppaying"] = 1; --Should players pay for props
CfgVars["propcost"] = 10; --Prop cost
CfgVars["letters"] = 1; --Allow letter writing
CfgVars["cpvoting"] = 1; --Allow CP voting
CfgVars["mayorvoting"] = 1; --Allow Mayor voting
CfgVars["cptomayoronly"] = 0; --Only CPs can do /votemayor
CfgVars["physgun"] = 1; --Physguns for everybody? 0 = Admins only

CfgVars["ak47cost"] = 2000
CfgVars["mp5cost"] = 1600
CfgVars["m16cost"] = 1400
CfgVars["mac10cost"] = 1100
CfgVars["umpcost"] = 1300
CfgVars["shotguncost"] = 1500
CfgVars["snipercost"] = 2200
CfgVars["flashbangcost"] = 250
CfgVars["grenadecost"] = 300
CfgVars["deaglecost"] = 210
CfgVars["fivesevencost"] = 230
CfgVars["glockcost"] = 220
CfgVars["p228cost"] = 200
CfgVars["druglabcost"] = 500
CfgVars["gunlabcost"] = 600
CfgVars["microwavecost"] = 400
CfgVars["microwavepayamount"] = 10
CfgVars["drugpayamount"] = 25
CfgVars["ammopistolcost"] = 20
CfgVars["ammoriflecost"] = 40
CfgVars["ammoshotguncost"] = 60
CfgVars["healthcost"] = 50
CfgVars["jailtimer"] = 40
CfgVars["whisperradius"] = 90
CfgVars["talkradius"] = 250
CfgVars["yellradius"] = 550
CfgVars["doorcost"] = 30
CfgVars["zombiescore"] = 10
CfgVars["microwavefoodcost"] = 40
CfgVars["maxdruglabs"] = 5
CfgVars["maxmicrowaves"] = 2
CfgVars["maxgunlabs"] = 2
CfgVars["allowgang"] = 1
CfgVars["maxgangsters"] = 6
CfgVars["allowmedics"] = 1
CfgVars["maxmedics"] = 6
CfgVars["allowdealers"] = 1
CfgVars["maxgundealers"] = 4
CfgVars["allowcooks"] = 1
CfgVars["maxcooks"] = 4
CfgVars["maxow"] = 5

CfgVars["upgradecost"] = 1 // upgrade cost is a multiplier of the thing's price. level 2 upgrade will be double of whats set here. 0 = free
// example: turret costs 300. first upgrade costs 300 which is the turret's cost, and second upgrade costs 600, which is double that.

CfgVars["afktime"] = 600

drugeffect_doubletapmod = 0.675
drugeffect_armorpiercermod = 1.25
drugeffect_shockwavemultiplier = 1